import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header";
import Nav from "../components/Nav";
import React from "react";
import Results from "/components/Results";
import requests from "../utils/requests";

export default function Home({results}) {
    return (
        <div>
            <Head>
                <title>Hulu 2.0</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header></Header>
            <Nav></Nav>
            <Results results={results}></Results>
        </div>
    )
}

export const getServerSideProps = async (context) => {
    const genre = context.query.genre;
    const response = await fetch(`http://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`);
    const result = await response.json();

    return {
        props : {
            results : result.results
        }
    }
}